### ISSUE TITLE
Transfer repo to SciKit-Surgery org 

### ISSUE THREAD

**Issue by mxochicale** [UCL/scikit-surgeryopencvcpp#32]
Hi @thompson318 , @tdowrick @MattClarkson 

Can we transfer this repo to https://github.com/SciKit-Surgery to keep a consistency naming of organisations? 

Happy to migrate repo/issues. I have done something similar in the pass following https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository , https://docs.github.com/en/enterprise-server@3.3/repositories/creating-and-managing-repositories/transferring-a-repository

Thanks

**Comment by thompson318** [comment]
Yes, we should. I haven't got admin permission on this one. @tdowrick or @MattClarkson please can you grant @mxochicale admin access.

**Comment by mxochicale** [comment]
Closing this one as repo was successfully transferred from UCL/scikit-surgeryopencvcpp to SciKit-Surgery/scikit-surgeryopencvcpp/
